"""
Imaginary service — configuration.
"""

SERVICE_NAME = "imaginary"
VERSION = "0.1.0"
DEBUG = False
MAX_RETRIES = 7
TIMEOUT_SECONDS = 30
LOG_LEVEL = 'INFO'
CACHE_TTL = 300
MAX_CONNECTIONS = 10
RETRY_DELAY = 1.5
QUEUE_SIZE = 100
